version: '2'

services:

### HA Proxy #######################################
  haproxy:
    image: dockercloud/haproxy
    links:
      - websrv
    environment:
      - COOKIE=${COOKIE}
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

### WEB APP #######################################
  websrv:
    build: app/BS1
    image: websrv
    environment:
      - COOKIE=${COOKIE}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - USER_ID=${USER_ID}
    env_file: .env
    ports:
      - 8081-8090:80
    depends_on:
      - mssql

### MSSQL SERVER #####################################
  mssql:
    container_name: mssql
    build:
      context: ./mssql
      args:
        - ACCEPT_EULA=${ACCEPT_EULA}
        - SA_PASSWORD=${SA_PASSWORD}
        - USER_ID=${USER_ID}
    env_file: .env
    volumes:
     - ./mssql/data:/var/opt/mssql/data/
    ports:
      - '1433:1433'