version: '2'

services:

### HA Proxy #######################################
  haproxy:
    image: dockercloud/haproxy
    links:
      - websrv
    environment:
      - COOKIE=SRV insert indirect nocache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

### WEB APP #######################################
  websrv:
    build: app/BS1
    image: websrv
    environment:
      - COOKIE=SRV insert indirect nocache
      - ASPNETCORE_ENVIRONMENT=Development
    ports: 
      - 8081-8090:80
    depends_on:
      - mssql

### MSSQL SERVER #####################################
  mssql:
    build: ./mssql
    container_name: mssql
    volumes:
     - ./mssql/data:/var/opt/mssql/data/
    ports:
      - '1433:1433'