version: '3.4'

services:

#### WEB SERVER ONE ###################################################

  web1:
    container_name: web1
#    image: dockercloud/hello-world
    image: nimble85/web_1:latest
    env_file: .env
    ports:
      - "81:80"
#      - "443:443"

#### WEB SERVER TWO ###################################################

  web2:
    container_name: web2
#    image: dockercloud/hello-world
    image: nimble85/web_1:latest

    env_file: .env
    ports:
      - "82:80"
#      - "443:443"docker tag

#### MYSQL SERVER ###################################################

#  mysql:
#    build: ./mssql
#    container_name: mysql

#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
   
#
#    environment:
#      ENV ACCEPT_EULA=Y
#      ENV SA_PASSWORD=VleDh%)yUB

#    env_file: .env
#    ports:
#      - "1433:1433"
  #      - "443:443"


### HA Proxy #######################################
#  haproxy:
##    build: ./haproxy
#    container_name: haproxy
#    image: 'dockercloud/haproxy:latest'
#    links:
#     - web1
#     - web2
#    env_file: .env
#    ports:
#      - "80:80"
##    volumes:
##      - ./haproxy:/usr/local/etc/haproxy



networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
